version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=123qwe

  api:
    image: postgrest/postgrest
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - PGRST_DB_URI=postgres://api:123qwe@db/api
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=postgres

  admin:
    image: fenglc/pgadmin4
    links:
      - db
    ports:
      - '3001:5050'
    environment:
      - DEFAULT_USER=api
      - DEFAULT_PASSWORD=123qwe
