version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=placeholder
      - POSTGRES_PASSWORD=placeholder

  admin:
    image: fenglc/pgadmin4
    links:
      - db
    ports:
      - '3001:5050'
    environment:
      - DEFAULT_USER=api
      - DEFAULT_PASSWORD=123qwe
  
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
